import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";

export default function Home() {
  const { isLoading, error, user } = useUser();

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={styles.nav}>
          <Link href="/">Go to back home page</Link>
          <Link href="/api/auth/login">Log in</Link>
          <Link href="/api/auth/logout">Log out</Link>
          <Link href="/private">Go to private page</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <section>
          {isLoading && <p>Loading</p>}
          {error && <p>{error.message}</p>}
          {user && (
            <div className={styles["user-card"]}>
              <div className={styles["user-card-avatar"]}>
                <Image
                  src={user.picture}
                  alt={user.nickname}
                  width={100}
                  height={100}
                />
              </div>
              <div className={styles["user-card-details"]}>
                <dl className={styles["user-card-list"]}>
                  <dt>Name</dt>
                  <dd>{user.name}</dd>
                  <dt>Email</dt>
                  <dd>
                    <a href={`mailto:${user.email}`}>{user.email}</a>
                  </dd>
                  <dt>ID (sub)</dt>
                  <dd>{user.sub}</dd>
                </dl>
              <pre>
                <code>{JSON.stringify(user, null, "\t")}</code>
              </pre>
              </div>
            </div>
          )}
          {!user && <p>No user logged in</p>}
        </section>
      </main>
    </>
  );
}
